name: Updating Client Broker Configs
on:
  push:
    branches: [main]
jobs:
  Branch-Update-clients:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update Vesselnet Client Broker
        run: |
          git remote update
          git fetch
          git checkout --track origin/main


      # - name: Update Vesselnet Client Broker
      #   run: |
      #     git checkout vesselnet-nigeria-configs
      #     git pull
      #     git rebase main
      #     git push -f

      # - name: Update Xsolar Client Broker
      #   run: |
      #     git checkout xsolar-config
      #     git pull
      #     git rebase main
      #     git push -f
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
